version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    ports:
      - "3000:3000"
    environment:
      TELEGRAM_BOT_API: ${TELEGRAM_BOT_API}
    volumes:
      - .:/usr/src/app
    restart: always
